package com.example.track_birr.data.local

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a financial transaction parsed from an SMS message.
 * This entity is stored locally in the Room database.
 */
@Entity(tableName = "expenses")
data class Expense(
    /**
     * Unique identifier for the transaction, auto-generated by the database.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    /**
     * The monetary value of the transaction.
     */
    val amount: Double,

    /**
     * The name of the merchant, person, or organization involved in the transaction.
     */
    @ColumnInfo(name = "merchant_name")
    val merchantName: String,

    /**
     * The exact UNIX timestamp (in milliseconds) when the SMS was received.
     */
    val timestamp: Long,

    /**
     * The financial institution or telecom service that processed the transaction 
     * (e.g., 'CBE', 'Telebirr', 'Awash Bank').
     */
    @ColumnInfo(name = "bank_or_telecom")
    val bankOrTelecom: String,

    /**
     * Indicates whether this transaction is an income (true) or an expense (false).
     * Useful for tracking money received versus money spent.
     */
    @ColumnInfo(name = "is_income")
    val isIncome: Boolean
)
